version: '3.7'
services:
  database_typescript:
    image: postgres
    container_name: dbForTypescript
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: typescript
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local